version: '3.3'

networks:
  backend: 

services:
  fastapi: 
    image: azsx26735546/senao-backend:latest
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - postgres
      - redis 
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
    
  postgres:
    image: postgres:latest
    expose:
      - "5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data 
  
  flyway:
    image: azsx26735546/senao-assessment_flyway:latest
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      - FLYWAY_URL=${FLYWAY_URL}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
volumes:
  postgres-data: